### ISSUE TITLE
Consider trying the faer feature of extendr! 

### ISSUE THREAD

**Issue by JosiahParry** [albersonmiranda/fio#39]
extendr added support for faer feature recently which may be able to help simplify some of your use cases. It might be worth exploring! 

You can see some examples of how it can be used at https://github.com/extendr/extendr/blob/544b38b141640199aaee86e589abaf8ec73c6601/tests/extendrtests/src/rust/src/optional_faer.rs#L2

**Comment by albersonmiranda** [comment]
@JosiahParry I'm missing something. When I do:

```
#[extendr]
fn rmat_to_mat(x: RMatrix<f64>) -> faer::Mat<f64> {
    faer::Mat::<f64>::from(x)
}
```
I get
```
mismatched types
expected struct `Mat<f64>`
   found struct `extendr_api::RArray<f64, [usize; 2]>`
```

**Comment by JosiahParry** [comment]
Have you added the feature on extendr?

**Comment by albersonmiranda** [comment]
How do I do that? Remember I have exactly 10 days of Rust 😅

**Comment by albersonmiranda** [comment]
Looks like that feature haven't been released on crates.io yet. Gotta put a pin on that.

**Comment by JosiahParry** [comment]
you can accomplish this by adding the following to your Cargo.toml
```
extendr = { git = "https://github.com/extendr/extendr", features = ["faer"] }
```

**Comment by albersonmiranda** [comment]
> you can accomplish this by adding the following to your Cargo.toml
> 
> ```
> extendr = { git = "https://github.com/extendr/extendr", features = ["faer"] }
> ```

That didn't work either. I could get it working with
```
[dependencies.extendr-api]
git = "https://github.com/extendr/extendr"
branch = "master"
features = ["faer"]
```
But
```
fn foo(x: RMatrix<f64>) -> RMatrix<f64> {

  // convert to faer matrix
  let tech_coeff_matrix = Mat::<f64>::from(x);
...
```
keeps throwing "expected struct `faer::Mat<f64>` found struct `extendr_api::RArray<f64, [usize; 2]>`"

Does anyone have a working reprex in a separate repo?
